- name: Create AWS configuration directory
  file:
    path: "~/.aws"
    state: directory
    mode: 0700
    owner: "{{ item.key }}"

- name: Create AWS configuration file
  template:
    src: "aws-config.j2"
    dest: "~/.aws/config"
    mode: 0600
    owner: "{{ item.key }}"
